### ISSUE TITLE
Implement injection of dependencies in the CallableDefinition in this package itself instead of using hardcoded Injector

### ISSUE THREAD

**Issue by yiiliveext** [yiisoft/definitions#4]
We use a hardcoded Injector to resolve `CallableDefinition` dependencies. I think it is not a good idea.
We should implement this in the package itself. We can use `DefinitionResolver::resolveArray()` and `DefinitionExtractor::fromMethod()` methods for this purpose if we make `DefinitionExtractor::fromMethod()` public.

**Comment by samdark** [comment]
Why isn't it a good idea?

**Comment by yiiliveext** [comment]
> Why isn't it a good idea?

Because we can use this package with a custom user container that uses its own injector.

**Comment by vjik** [comment]
Closed by #6
